require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
  - rubocop-factory_bot
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Metrics/MethodLength:
  Max: 30
